export const START_FETCH = 'RECIPES_START_FETCH';
export const FETCH_SUCCESS = 'RECIPES_FETCH_SUCCESS';
export const FETCH_FAILED= 'RECIPES_FETCH_FAILED';
export const START_UPDATE = 'RECIPES_START_UPDATE';
export const UPDATE_SUCCESS = 'RECIPES_UPDATE_SUCCESS';
export const UPDATE_FAILED= 'RECIPES_UPDATE_FAILED';
