export const START_FETCH = 'RECIPES_START_FETCH';
export const FETCH_SUCCEEDED = 'RECIPES_FETCH_SUCCEEDED';
export const FETCH_FAILED= 'RECIPES_FETCH_FAILED';
export const START_UPDATE = 'RECIPES_START_UPDATE';
export const UPDATE_SUCCEEDED = 'RECIPES_UPDATE_SUCCEEDED';
export const UPDATE_FAILED= 'RECIPES_UPDATE_FAILED';
