const NAMESPACE = '[Recipes] ';
export const START_FETCH = NAMESPACE + 'START_FETCH';
export const FETCH_COMPLETE = NAMESPACE + 'FETCH_COMPLETE';
export const FETCH_FAILED = NAMESPACE + 'FETCH_FAILED';
export const START_UPDATE = NAMESPACE + 'START_UPDATE';
export const UPDATE_COMPLETE = NAMESPACE + 'UPDATE_COMPLETE';
export const UPDATE_FAILED = NAMESPACE + 'UPDATE_FAILED';
