import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="dark:bg-stone-900 dark:text-stone-300 font-extralight">
        <Link href="/import">SETTINGS</Link>
        {children}
      </body>
    </html>
  );
}
